name: mini_e_learning
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  dio: ^5.1.1
  form_builder_validators: ^8.4.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  flutter_widget_from_html: ^0.9.1
  shimmer: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/

